---
- name: Download Rabbitmq Exporter to local folder
  become: no
  get_url:
    url: "{{ rabbitmq_exporter_download_url }}"
    dest: "/tmp/rabbitmq_exporter-{{ rabbitmq_exporter_version }}.tar.gz"
  run_once: true
  delegate_to: localhost

- name: Propagate Rabbitmq Exporter
  copy:
   src: /tmp/rabbitmq_exporter-{{ rabbitmq_exporter_version }}.tar.gz
   dest: "/tmp/rabbitmq_exporter-{{ rabbitmq_exporter_version }}.tar.gz"

- name: Extract Rabbitmq Exporter into the install directory
  unarchive:
    src: "/tmp/rabbitmq_exporter-{{ rabbitmq_exporter_version }}.tar.gz"
    dest: "/opt/"
    copy: no
    creates: "/opt/rabbitmq_exporter"

- name: Create a symlink for /opt/rabbitmq_exporter
  file:
    src: "/opt/rabbitmq_exporter-{{ rabbitmq_exporter_version }}.linux-amd64"
    dest: /opt/rabbitmq_exporter
    state: link

- name: Copy the Rabbitmq Exporter systemd service file
  template:
    src: etc/systemd/system/rabbitmq_exporter.service.j2
    dest: /etc/systemd/system/rabbitmq_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart rabbitmq_exporter

- name: Ensure Rabbitmq Exporter is started and enabled on boot
  systemd:
    name: rabbitmq_exporter
    state: started
    enabled: yes
