---
- name: Ensure rabbitmq is active
  wait_for:
    host: "{{ rabbitmq_address }}"
    port: "{{ rabbitmq_port }}"

# Create vhosts first for dependant exchanges
- name: create vhosts
  rabbitmq_vhost:
    name: "{{ item }}"
    state: present
  with_items: "{{ rabbitmq_vhosts }}"
