---
- name: restart rabbitmq
  service:
    name: rabbitmq-server
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart rabbitmq_exporter
  service:
    name: rabbitmq_exporter
    state: restarted
