---
- name: restart rabbitmq
  systemd:
    daemon_reload: yes
    name: rabbitmq-server
    state: restarted

- name: restart rabbitmq_exporter
  systemd:
    daemon_reload: yes
    name: rabbitmq_exporter
    state: restarted
